export const mapping = {
    'username'     : { type: 'string' },
    'geo.ip'       : { type: 'string' },
    'geo.country'  : { type: 'string' },
    'geo.provider' : { type: 'string' },
    'geo.cli'      : { type: 'string' },
    'geo.serial.as': { type: 'number' },
    'geo.serial.ss': { type: 'string' },
    'geo.serial.cn': { type: 'string' },
    'ban'          : { type: 'nested' },
    'ban.username' : { type: 'string' },
    'ban.ip'       : { type: 'string' },
    'ban.reason'   : { type: 'number' },
    'ban.serial'   : { type: 'nested' },
    'ban.serial.as': { type: 'string' },
    'ban.serial.ss': { type: 'string' },
    'ban.serial.cn': { type: 'string' },
    'chat'         : { type: 'nested' },
    'chat.username': { type: 'string' },
    'chat.type'    : { type: 'string' },
    'chat.message' : { type: 'string' },
    'gun'          : { type: 'nested' },
    'gun.id'       : { type: 'number' }
};