export enum ErrorCode {
    UNSUPPORTED_PLATFORM = 0x01,
    NOT_ALLOWED_BY_CORS,
    PARAM_MISSING,
    CHILD_PROCESS_ALREADY_SERVED,
    CHILD_PROCESS_IS_NOT_EXISTS,
    CHILD_PROCESS_CANT_KILL,
    CHILD_PROCESS_CANT_SERVE,
}